### ISSUE TITLE
Watch URL gets scuffed sometimes

### ISSUE THREAD

**Issue by ghost** [debsishu/Miyou-FrontEnd#2]
I'm pretty sure this only happens with animes with long names
https://streamable.com/0elg55

**Comment by debsishu** [comment]
> I'm pretty sure this only happens with animes with long names https://streamable.com/0elg55

No, the issue is with gogoanime. This anime starts with episode 0 numbered. and for some reason it errors out while scrapping the episode 0. 
[https://www.miyou.tk/watch/fategrand-order-zettai-majuu-sensen-babylonia-episode-1](https://www.miyou.tk/watch/fategrand-order-zettai-majuu-sensen-babylonia-episode-1) but if you play from this it plays fine

**Comment by ghost** [comment]
Ohhh
