### ISSUE TITLE
Telegram bot & login ?

### ISSUE THREAD

**Issue by titu3e** [debsishu/Miyou-FrontEnd#9]
you can integrate your website with a telegram bot that can show anime availability and download it and also give info bout anime

And You should also add a login feature

**Comment by jeydinpham** [comment]
Login would be cool, it could save the currently watching anime and we could favorite animes

**Comment by titu3e** [comment]
> Login would be cool, it could save the currently watching anime and we could favorite animes

yah but bot would be good too since theres no such thing as anime download bot in telegram

**Comment by debsishu** [comment]
> Login would be cool, it could save the currently watching anime and we could favorite animes

Yes, I've been thinking of implementing that, but before that, I want to change the structure of the site. Currently, Anilist API is being fetched from the backend. But due to Anilist's restrictions, we cannot do more than 90 calls per minute from an IP address. Currently, the site doesn't have that much traffic so it is not an issue. But for future-proofing, I want to move the Anilist API calling part to the front end so the IP will be depended on the user, not the server. This way API will not get rate limited.

**Comment by titu3e** [comment]
> > Login would be cool, it could save the currently watching anime and we could favorite animes
> 
> Yes, I've been thinking of implementing that, but before that, I want to change the structure of the site. Currently, Anilist API is being fetched from the backend. But due to Anilist's restrictions, we cannot do more than 90 calls per minute from an IP address. Currently, the site doesn't have that much traffic so it is not an issue. But for future-proofing, I want to move the Anilist API calling part to the front end so the IP will be depended on the user, not the server. This way API will not get rate limited.

but what about the bot?

**Comment by jeydinpham** [comment]
Why do you need anime in telegram?

**Comment by titu3e** [comment]
> Why do you need anime in telegram?

i makes easy to find animes download them
